source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SwiftNavicon_Example', :exclusive => true do
  pod "SwiftNavicon", :path => "../"
end

target 'SwiftNavicon_Tests', :exclusive => true do
  pod "SwiftNavicon", :path => "../"

  
end
